name: CI - Backend
 
on:
  pull_request:
    branches: [ main ]

jobs:
  check-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependências
        run: cd backend && npm install

      - name: Verificar se o servidor sobe
        run: cd backend && npm start &
