name: Continuous Delivery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Compactar projeto
        run: |
          zip -r projeto-entregavel.zip backend frontend README.md

      - name: Enviar artefato
        uses: actions/upload-artifact@v4
        with:
          name: projeto-entregavel
          path: projeto-entregavel.zip

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: projeto-entregavel

      - name: Ver arquivos baixados (debug)
        run: ls -R

      - name: Descompactar projeto
        run: unzip projeto-entregavel.zip

      - name: Simulando o deploy
        run: echo "Deploy realizado com sucesso!"
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
        
      - name: Build da imagem Docker
        run: |
          cd backend
          docker build -t ideationhub-backend .
        
      - name: Rodar o container Docker
        run: |
          cd backend
          docker run -d -p 4000:4000 --name ideationhub-backend ideationhub-backend       
          
      - name: Verificar se o container está rodando
        run: |
          if [ "$(docker ps -q -f name=ideationhub-backend)" ]; then
            echo "Container está rodando."
          else
            echo "Container não está rodando."
            exit 1
          fi