name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  check-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: |
          cd backend
          npm ci || npm install

      - name: Verificar lint (opcional)
        run: |
          cd backend
          npm run lint || echo "Lint não configurado ainda."

      - name: Verificar se o servidor sobe
    
        run: |
          cd backend
          if [ -f "index.js" ]; then
            node index.js &
          elif [ -f "app.js" ]; then
            node app.js &
          elif [ -f "server.js" ]; then
            node server.js &
          else
            echo "Main server file not found. Usando npm start..."
            npm start &
          fi
          sleep 5

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build da imagem Docker
        run: |
          cd backend
          docker build -t meu-backend .
  